# Generated by Django 5.0.3 on 2024-03-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_name', models.CharField(max_length=100)),
                ('kid_age', models.CharField(max_length=100)),
                ('kid_gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_description', models.CharField(max_length=100)),
                ('location_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('manufacturer_location', models.CharField(max_length=100)),
                ('manufacturer_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.CharField(max_length=100)),
                ('rating_date', models.CharField(max_length=100)),
                ('reviewer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ToyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_name', models.CharField(max_length=100)),
                ('toy_category', models.CharField(max_length=100)),
                ('toy_price', models.CharField(max_length=100)),
            ],
        ),
    ]
