# Generated by Django 5.0.6 on 2024-06-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signInUpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='User_Type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=100, null=True),
        ),
    ]
