# Generated by Django 5.0.3 on 2024-04-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=100)),
                ('Company_name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Company_description', models.TextField()),
                ('Job_description', models.TextField()),
                ('Qualification', models.CharField(max_length=100)),
                ('Salary_information', models.CharField(max_length=100)),
                ('Deadline', models.DateField(auto_now_add=True)),
                ('Designation', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='blood_group',
            field=models.CharField(choices=[('a+', 'A Positive'), ('a-', 'A Negative'), ('b+', 'B Positive'), ('b-', 'B Negative'), ('ab+', 'AB Positive'), ('ab-', 'AB Negative'), ('o+', 'O Positive'), ('o-', 'O Negative')], max_length=100),
        ),
    ]
