# Generated by Django 5.0.3 on 2024-04-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_universitymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='TeacherImage',
            field=models.ImageField(null=True, upload_to='', verbose_name='media/Teacher_Image'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='City',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='Department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
