# Generated by Django 5.0.3 on 2024-04-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_teachermodel_teacherimage_alter_teachermodel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='TeacherImage',
            field=models.ImageField(null=True, upload_to='media/Teacher_Image'),
        ),
    ]
