# Generated by Django 5.0.3 on 2024-04-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_alter_teachermodel_teacherimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='StudentImage',
            field=models.ImageField(null=True, upload_to='meadia/StudentImage/'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='City',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
