# Generated by Django 5.0.6 on 2024-05-23 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0002_alter_customusermodel_gender_basicinfomodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('company_description', models.TextField()),
                ('job_description', models.TextField()),
                ('qualification', models.CharField(max_length=100)),
                ('salary_information', models.CharField(max_length=100)),
                ('deadline', models.DateField(auto_now_add=True)),
                ('designation', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
