# Generated by Django 5.0.6 on 2024-05-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0003_addjobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjobmodel',
            name='deadline',
            field=models.DateField(),
        ),
    ]
