# Generated by Django 5.0.3 on 2024-04-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_universitymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='StudentImage',
            field=models.ImageField(null=True, upload_to='media/StudentImages'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='City',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
