# Generated by Django 5.0.3 on 2024-03-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_author', models.CharField(max_length=100)),
                ('blog_date', models.CharField(max_length=100)),
            ],
        ),
    ]
