# Generated by Django 5.0.4 on 2024-04-28 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=100)),
                ('Instructions', models.TextField()),
                ('preparation_time', models.CharField(max_length=100)),
                ('cooking_time', models.CharField(max_length=100)),
                ('total_time', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('nutritional_info', models.TextField()),
                ('recipe_image', models.ImageField(upload_to='static/recipe_image')),
                ('recipe_category', models.CharField(choices=[('breakfast', 'Breakfast'), ('launch', 'Launch'), ('dinner', 'Dinner')], max_length=50)),
                ('user_tags', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non-vegetarian', 'Non Vegetarian')], max_length=50)),
                ('total_calorie', models.CharField(max_length=40)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
