# Generated by Django 5.0.6 on 2024-06-19 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Number_openings', models.IntegerField()),
                ('Category', models.CharField(max_length=100)),
                ('Job_description', models.TextField()),
                ('Skills', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('recruiteruser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitermodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skills', models.CharField(max_length=100)),
                ('Resume', models.FileField(upload_to='media/seekerResume')),
                ('seekeruser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seekermodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
