# Generated by Django 5.0.6 on 2024-06-19 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0002_jobmodel_recruitermodel_seekermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='media/profile_picture'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Job Recruiter'), ('seeker', 'Job Seeker')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='Category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='Job_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='Number_openings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='Skills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruitermodel',
            name='company_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recruitermodel',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recruitermodel',
            name='recruiteruser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitermodel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seekermodel',
            name='Resume',
            field=models.FileField(null=True, upload_to='media/seekerResume'),
        ),
        migrations.AlterField(
            model_name='seekermodel',
            name='Skills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seekermodel',
            name='seekeruser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seekermodel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JobApplymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100, null=True)),
                ('resume', models.FileField(null=True, upload_to='media/applyResume')),
                ('status', models.CharField(default='Pending', max_length=100, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('applied_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobApp.jobmodel')),
            ],
        ),
    ]
