# Generated by Django 5.0.6 on 2024-06-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_priority',
            field=models.CharField(choices=[('hig', 'High'), ('low', 'Low'), ('medium', 'Medium')], max_length=100, null=True),
        ),
    ]
