# Generated by Django 5.0.6 on 2024-06-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_taskmodel_task_priority'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorymodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taskmodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_priority',
            field=models.CharField(choices=[('medium', 'Medium'), ('hig', 'High'), ('low', 'Low')], max_length=100, null=True),
        ),
    ]
