# Generated by Django 5.0.6 on 2024-06-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_alter_customusermodel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=100, null=True),
        ),
    ]
