# Generated by Django 5.0.6 on 2024-06-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0005_alter_customusermodel_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'ordering': ['username'], 'verbose_name': 'Custom user', 'verbose_name_plural': 'Custom users'},
        ),
        migrations.AlterUniqueTogether(
            name='customusermodel',
            unique_together={('email', 'username')},
        ),
        migrations.AlterModelTable(
            name='customusermodel',
            table='my_todo_list_table',
        ),
    ]
