# Generated by Django 5.0.6 on 2024-06-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0006_alter_customusermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=100, null=True),
        ),
    ]
