# Generated by Django 5.0.6 on 2024-06-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0007_alter_customusermodel_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['category_name'], 'verbose_name': 'Category Model', 'verbose_name_plural': 'Category Models'},
        ),
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'ordering': ['username'], 'verbose_name': 'Custom User Model', 'verbose_name_plural': 'Custom User Models'},
        ),
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ['due_date'], 'verbose_name': 'Task Model', 'verbose_name_plural': 'Task Models'},
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='completed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='task_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='task_priority',
            field=models.CharField(choices=[('hig', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='task_status',
            field=models.CharField(default='on_going', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='categorymodel',
            unique_together={('user',)},
        ),
        migrations.AlterUniqueTogether(
            name='taskmodel',
            unique_together={('category',)},
        ),
        migrations.AlterModelTable(
            name='categorymodel',
            table='todo_list_category_table',
        ),
        migrations.AlterModelTable(
            name='taskmodel',
            table='todo_list_task_table',
        ),
    ]
