# Generated by Django 5.0.6 on 2024-06-05 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0002_alter_customusermodel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Job Recruiter'), ('seeker', 'Job Seeker')], max_length=100),
        ),
        migrations.CreateModel(
            name='ApplyJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='media/seeker_resume')),
                ('seeker_profile_pic', models.ImageField(upload_to='media/seeker_profile_pic')),
                ('qualifications', models.FileField(upload_to='media/seeker_resume')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobApp.jobmodel')),
            ],
        ),
    ]
