# Generated by Django 5.0.6 on 2024-06-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0003_alter_customusermodel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobmodel',
            name='qualifications',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=100),
        ),
    ]
