# Generated by Django 5.0.4 on 2024-05-06 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='last_education',
            field=models.CharField(choices=[('jsc', 'JSC'), ('ssc', 'SSC'), ('hsc', 'HSC')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
